url: https://smes.nekox.net
baseurl: /

# Site settings
title: Swinburne Mechatronics Engineering Society
email: mechatronics.swin@gmail.com
description: "The homepage for the Swinburne Mechatronics Engineering Society, a club at Swinburne University of Technology, Melbourne, Australia, aimed at bringing industry closer to our mechatronics engineering students."


# Team names, titles and social links
people:
- name: David Di Meo
  pic: 1
  position: President and Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/daviddimeo/

- name: Monique Kuhn
  pic: 2
  position: Lead Designer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/monique-kuhn/
    - title: link
      url: https://www.wabinabi.com/

- name: Jacob Walker
  pic: 3
  position: Treasurer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jacob-walker-788970189/

- name: Stuart Cafarella
  pic: 4
  position: Secretary
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/stuartcafarella/

- name: Jimmy Trac
  pic: 5
  position: Lead Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jimmy-trac/
    - title: github
      url: https://github.com/mikanwolfe
    - title: link
      url: https://nekox.net/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/mechatronics.swin/
  - title: university
    url: https://studentlife.swinburne.edu.au/Clubs/Mechatronics
  - title: linkedin
    url: https://www.linkedin.com/company/mechatronics-swin/

# Postal address (add as many lines as necessary)
address:
  - line: Swinburne University of Technology,
  - line: John Street, Hawthorn VIC 3122, Australia

# Build settings
markdown: kramdown
permalink: pretty